# mysql 설정
oauth:
  kakao:
    client-id: 160cd4f66fc928d2b279d78999d6d018
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com

spring:
  profiles:
    active: profile1
    group:
      dev: profile1

logging:
  level:
    root: info


---     
spring:
  config:
    activate:
      on-profile: profile1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    url: jdbc:mysql://database-1.cf82kp3ku9xz.ap-northeast-2.rds.amazonaws.com:3306/FWLTC2?autoReconnect=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    password: '12345678'
    hikari:
      validation-timeout: 300000
  jpa:
    properties:
      hibernate:
        "[format_sql]": 'true'
        "[use_sql_comments]": 'true'
        "[show_sql]": 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: create
